apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /jupiter
            pathType: Prefix
            backend:
              service:
                name: jupiter
                port:
                  number: 80
          - path: /mars
            pathType: Prefix
            backend:
              service:
                name: mars
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: planet
                port:
                  number: 80